# Veracode Demo to Azure Pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: VERACODE_API

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: Maven@4
    displayName: Compile VeraDemo
    inputs:
      mavenPomFile: 'app/pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - publish: $(System.DefaultWorkingDirectory)/app/target/verademo.war
    displayName: 'Publish Artifact'
    artifact: WARCompiled

- job: VeracodeScan
  displayName: 'Veracode Scan Pipeline'
  dependsOn: BuildAndTest
  steps:
  - download: current
    artifact: WARCompiled
    displayName: 'Download Artifacts'
    
  - task: Bash@3
    displayName: Local Veracode Pipeline/Scan
    inputs:
      targetType: 'inline'
      script: |
        curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip
        java -jar pipeline-scan.jar -vid $(VERACODE_API_ID) -vkey $(VERACODE_API_KEY) -f $(System.DefaultWorkingDirectory)/WARCompiled/verademo.war || true


