name: ASP.NET Build and Veracode Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup NuGet
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    # Restore NuGet packages
    - name: Restore NuGet Packages
      run: nuget restore ${{ vars.solution }}

    # Build the solution
    - name: Build Solution
      run: msbuild ${{ vars.solution }} /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(System.DefaultWorkingDirectory)/artifacts" /p:Platform=${{ vars.buildPlatform }} /p:Configuration=${{ vars.buildConfiguration }}

    # Download and run Veracode Static Pipeline Scanner
    - name: Veracode Static Pipeline Scanner
      run: |
        curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip
        java -jar pipeline-scan.jar -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} -f $(System.DefaultWorkingDirectory)/artifacts/Verademo-dotnet.zip || true

    # Publish artifacts
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: veracode-scan-results
        path: results.json
