name: Build and Veracode Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '8'
          distribution: 'adopt'

      # Build with Maven
      - name: Build with Maven
        run: mvn -f app/pom.xml package

      # Veracode Static Pipeline Scanner
      - name: Veracode Static Pipeline Scanner
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} -f app/target/verademo.war || true

      # Upload Veracode results as an artifact
      - name: Upload Veracode Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: VeracodeBaseline
          path: results.json
