name: Build and Veracode Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this to enable manual trigger from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '8'
          distribution: 'adopt'

      # Build with Maven
      - name: Build with Maven
        run: mvn -f app/pom.xml package

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
            createprofile: true
            filepath: app/target/verademo.war
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            debug: true

      # Upload Veracode results as an artifact
      - name: Upload Veracode Scan Results
        uses: actions/upload-artifact@v3
        with:
          name: VeracodeBaseline
          path: results.json
