---
name: SBOM

on:
  workflow_dispatch:

jobs:
  sbom:
    name: setup
    runs-on: ubuntu-latest
    container: 
      image: veracode/api-signing:latest
    env:
      VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
      VERACODE_API_KEY_SECRET : ${{ secrets.VERACODE_API_KEY }}

    steps:
      - name: HelloWorld
        run: |
          app_guid = $(http --auth-type=veracode_hmac GET "https://api.veracode.com/appsec/v1/applications" "legacy_id == ${{ secrets.VERACODE_APP_ID }} | jq -r '._embedded.applications[0].guid"
          http --auth_type=veracode_hmac GET "https://api.veracode.com/srcclr/sbom/v1/targets/${{ app_guid }}" "type==application"          
