---
name: SBOM

on:
  workflow_dispatch:

jobs:
  sbom:
    name: setup
    runs-on: ubuntu-latest
    container: 
      image: veracode/api-signing:latest
    env:
      VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
      VERACODE_API_KEY_SECRET : ${{ secrets.VERACODE_API_KEY }}

    steps:
      - name: HelloWorld
        run: | 
          appguid=$(http --auth-type=veracode_hmac GET "https://api.veracode.com/appsec/v1/applications?legacy_id=301001" | jq -r '._embedded.applications[0].guid')
          echo GUID: ${appguid}
