---
name: SBOM

on:
  workflow_dispatch:

jobs:
  sbom:
    name: setup
    runs-on: ubuntu-latest
    container: 
      image: veracode/api-signing:latest
    env:
      VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
      VERACODE_API_KEY_SECRET : ${{ secrets.VERACODE_API_KEY }}

    steps:
      - name: HelloWorld
        run: |
          http --auth-type=veracode_hmac "https://api.veracode.com/appsec/v1/applications"         
