---
name: SBOM

on:
  workflow_dispatch:

jobs:
  sbom:
    name: setup
    runs-on: veracode/api-signing:cmd
    env:
      VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
      VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "pypy3"]

    steps:
      - name: HelloWorld
        run: |
          https://api.veracode.com/api/authn/v2/users/self          
