            - name: Veracode scan results to GitHub issues Action
  # You may pin to the exact commit or the version.
  # uses: veracode/veracode-flaws-to-issues@9cff79e532c36d9686c7dd1876a4df64232e4457
  uses: veracode/veracode-flaws-to-issues@v2.1.20
  with:
    # Scan results file
    scan-results-json: # default is filtered_results.json
    # GitHub token to access the repo
    github-token: # default is ${{ github.token }}
    # Delay (in seconds) between entering Issues into GitHub (due to rate limiting)
    wait-time: # optional, default is 2
    # Rewrite 1
    source_base_path_1: # optional
    # Rewrite 2
    source_base_path_2: # optional
    # Rewrite 3
    source_base_path_3: # optional
    # fail pipeline upon findings (true | false)
    fail_build: # optional
    # enable debug logging
    debug: # optional
          
